### ISSUE TITLE
Library zone sort data warning

### ISSUE THREAD

**Issue by i23409asd0asdjfo** [PunishedPineapple/WaymarkPresetPlugin#24]
--------------------------------
10:14:58.828 | WRN [WaymarkPresetPlugin] Unable to load library zone sort data:
System.IO.FileNotFoundException: Could not find file 'C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\WaymarkPresetPlugin\LibraryZoneSortData_v1.json'.
File name: 'C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\WaymarkPresetPlugin\LibraryZoneSortData_v1.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at WaymarkPresetPlugin.Window_Library..ctor(PluginUI UI, DalamudPluginInterface pluginInterface, GameGui gameGui, Configuration configuration, ClientState clientState, IntPtr pLibraryZoneDragAndDropData, IntPtr pLibraryPresetDragAndDropData)
{ } [ Send ]

**Comment by PunishedPineapple** [comment]
This is fine; it's just a warning because it doesn't see a sort file to load.  I do actually have uncommitted changes for the next version that change the error level of this and other thing when it's file not found, but what you're seeing is intentional.  Non-errors in your log can be ignored unless you're having issues, which is when we'd look at the log.
